### ISSUE TITLE
Can't locate Date/Holidays/Adapter/ca_es.pm

### ISSUE THREAD

**Issue by eserte** [miquelruiz/Date-Holidays-CA_ES#2]
The test suite started to fail:
```
Unable to load module: Date::Holidays::Adapter::ca_es - Unable to load: Date::Holidays::Adapter::ca_es - Can't locate Date/Holidays/Adapter/ca_es.pm in @INC (@INC contains: /usr/home/eserte/.cpan/build/2018060909/Date-Holidays-CA_ES-0.03-3/blib/lib /usr/home/eserte/.cpan/build/2018060909/Date-Holidays-CA_ES-0.03-3/blib/arch /usr/perl5.16.3t/lib/site_perl/5.16.3/amd64-freebsd-thread-multi /usr/perl5.16.3t/lib/site_perl/5.16.3 /usr/perl5.16.3t/lib/5.16.3/amd64-freebsd-thread-multi /usr/perl5.16.3t/lib/5.16.3 .) at /usr/perl5.16.3t/lib/site_perl/5.16.3/Module/Load.pm line 77.
Can't locate Date/Holidays/Adapter/ca_es in @INC (@INC contains: /usr/home/eserte/.cpan/build/2018060909/Date-Holidays-CA_ES-0.03-3/blib/lib /usr/home/eserte/.cpan/build/2018060909/Date-Holidays-CA_ES-0.03-3/blib/arch /usr/perl5.16.3t/lib/site_perl/5.16.3/amd64-freebsd-thread-multi /usr/perl5.16.3t/lib/site_perl/5.16.3 /usr/perl5.16.3t/lib/5.16.3/amd64-freebsd-thread-multi /usr/perl5.16.3t/lib/5.16.3 .) at /usr/perl5.16.3t/lib/site_perl/5.16.3/Module/Load.pm line 77.
...
# Looks like your test exited with 2 just after 1.
t/02-ca_es.t ........ 
Dubious, test returned 2 (wstat 512, 0x200)
Failed 10/11 subtests 
```

Maybe this happens with newer Date::Holidays (@jonasbn: FYI).

**Comment by jonasbn** [comment]
My opinion is that this issue should be closed, since the issue is with Date::Holidays and not with the Date::Holidays::CA_ES distribution. The distribution could be adjusted for easy adaptation, but due to the naming and the scope and the implementation of Date::Holidays and adaptation would be required to be implemented in Date::Holidays

**Comment by eserte** [comment]
@jonasbn I think this issue may still be left open --- once Date::Holidays is fixed Date::Holidays::CA_ES could mark Date::Holidays with a minimum prereq version as a dependency to make sure that the problematic versions are upgraded.

**Comment by jonasbn** [comment]
Hi @eserte support for Date::Holidays::CA_ES has been added with [release 1.13](https://github.com/jonasbn/perl-date-holidays/releases/tag/1.13). 

> 1.13 2018-06-12 Feature release, update recommended
>
> This release integrates Date::Holidays::CA_ES is does so
> by supporting the region parameter with the value 'ca' via
> Date::Holidays::ES

The module is not supported directly, but as described earlier it is identified as a region ('CA') in Spain ('ES').

Example:

```perl
use Date::Holidays;

my $dh = Date::Holidays->new( countrycode => 'es' );

if ($dh->is_holiday(year => 2017, month  => 6, day => 24, region => 'ca')) {
    print "Yes it is a Catalan holiday\n";
}

my $holidays = $dh->holidays( year => 2006, region => 'ca' );
```

If you do want to view Catalonia as a region in Spain, you can use it directly:

```perl
use Date::Holidays;

my $dh = Date::Holidays->new( countrycode => 'CA_ES', nocheck => 1 );

if ($dh->is_holiday(year => 2017, month  => 6, day => 24)) {
    print "Yes it is a Catalan holiday\n";
}

my $holidays = $dh->holidays( year => 2006);
```

I plan to discontinue the `nocheck` parameter for something more elegant, more on this in a future release.

**Comment by miquelruiz** [comment]
Re-enabled tests in 5d28195a32d7aefce83e0bde167ab33b312a1ad1
